Update README.md
e111077/11ty-lit pull request #5
Opened 2024-10-24 05:57 UTC by tgallagher2017

Add more documentation.

2024-10-24 06:12 UTC, e111077 requested changes
Thanks so much for the submission! Just one small request

2024-10-24 06:12 UTC, e111077 commented on README.md
> +This holds files that include 'import' notation to import the components used in server side rendering (SSR) and require hydration. The pages with .ts extention match the structure and name as those
Wording is a bit cloudy here. Can you include a code block example please?

2024-12-06 06:20 UTC, tgallagher2017 commented
Hi,

Sorry for the delay in updating the README. I was busy finishing writing my
novel. Now I'm back to writing software.

Tim


On Thu, Oct 24, 2024 at 12:12 AM Elliott Marquez ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
> Thanks so much for the submission! Just one small request
> ------------------------------
>
> In README.md
> <https://github.com/e111077/11ty-lit/pull/5#discussion_r1814324420>:
>
> > @@ -57,9 +58,13 @@ Most of these are for templating in 11ty. See the 11ty docs for more info. If yo
>
>  This directory holds your Lit components. If you add a component here, to hook it up to SSR, add it to the `src/ssr.ts` file and make sure to add it to `tsEntrypoints` in `esbuild.config.mjs` to make sure it's included in the bundler. If you don't want to SSR a component, you can add it to the appropriate file in `src/pages/<your page name>.ts`;
>
> +#### `site/hydration-entrypoints`
> +
> +This holds files that include 'import' notation to import the components used in server side rendering (SSR) and require hydration. The pages with .ts extention match the structure and name as those files in the `site` folder.
>
> Wording is a bit cloudy here. Can you include a code block example please?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/e111077/11ty-lit/pull/5#pullrequestreview-2391392293>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AGRBVLHIHYHGSL7GUHUWVDDZ5CFWDAVCNFSM6AAAAABQQJCLFKVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDGOJRGM4TEMRZGM>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-12-06 07:15 UTC, e111077 approved these changes
Congrats on the novel!

2024-12-06 07:15 UTC, merged